### ISSUE TITLE
Move the search function

### ISSUE THREAD

**Issue by PixPanz** [jghibiki/Doc#25]
I feel the desktop UI would be more convenient if the search function was placed above the favorites bar on the right side of the screen.

**Comment by PixPanz** [comment]
I kind of figured that was the case. I think that move you've suggested would at least be worth looking into, it just seems like the search function should be at the top of the page.

**Comment by jghibiki** [comment]
What i ended up doing, was moving search above volume and then compressing volume a bit so it all hopefully fits better on most screens. Search just didn't look good above queue because of all the horizontal space it wasted. This change is deployed to the acm music box as of this morning.
